name: build and test frontend
on:
  push:
    branches:
      - '*'
# 2 parallel jobs: build and test
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: sudo apt-get install -y parallel
      - run: parallel "sudo apt-get install -y mongodb-org" "parallel npm run i --prefix ::: api ngapp"
      - run: bash mongotest/start.sh &
      - run: FUDGE=1 NO_EMAILS=1 npm run --prefix api start &
      - run: "parallel npm run --prefix ngapp ::: e2e test:ci build:prod build:qa"
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'ngapp/qa_build'
          push: true

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: 3.6
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install --prefix api
      - run: npm run test --prefix api 
