name: build and test frontend
on:
  push:
    branches:
      - '*'
# 2 parallel jobs: build and test
jobs:
  build-frontend-prod:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install ngapp Dependencies
        run: npm install --prefix ngapp
      - name: build:prod
        run: npm run build:prod --prefix ngapp
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'ngapp/unpublished_dist'
          push: true

  build-frontend-qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install ngapp Dependencies
        run: npm install --prefix ngapp
      - name: build:qa
        run: npm run build:qa --prefix ngapp
      - uses: EndBug/add-and-commit@v9
        with:
          add: 'ngapp/qa_build'
          push: true

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - uses: browser-actions/setup-chrome@latest
      - name: Install ngapp Dependencies
        run: npm install --prefix ngapp
      - name: ng test
        run: npm run test:ci --prefix ngapp

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Start MonoDB
        uses: supercharge/mongodb-github-action@1.2.0
        with:
          mongodb-version: [3.6, 4.0]
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install api Dependencies
        run: npm install --prefix api
      - name: test
        run: npm run test --prefix api 
